{% set version = '2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsqlite
  version: {{ version|replace("-", "_") }}

source:
  fn: RSQLite_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/RSQLite_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/RSQLite/RSQLite_{{ version }}.tar.gz
  sha256: 7f0fe629f34641c6af1e8a34412f3089ee2d184853843209d97ffe29430ceff6


  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: DBItest, knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-bh
    - r-dbi >=0.4_9
    - r-rcpp >=0.12.7
    - r-bit64
    - r-blob >=1.1
    - r-memoise
    - r-pkgconfig
    - r-plogr

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-dbi >=0.4_9
    - r-rcpp >=0.12.7
    - r-bit64
    - r-blob >=1.1
    - r-memoise
    - r-pkgconfig
    - r-plogr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RSQLite')"           # [not win]
    - "\"%R%\" -e \"library('RSQLite')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rstats-db/RSQLite
  license: LGPL (>= 2)
  summary: Embeds the 'SQLite' database engine in R and provides an interface compliant with
    the 'DBI' package. The source for the 'SQLite' engine (version 3.8.8.2) is included.
  license_family: LGPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: RSQLite
# Version: 2.0
# Date: 2017-06-18
# Title: 'SQLite' Interface for R
# Authors@R: c( person("Kirill", "Muller", role = c("aut", "cre"), email = "krlmlr+r@mailbox.org"), person("Hadley", "Wickham", role = c("aut")), person(c("David", "A."), "James", role = "aut"), person("Seth", "Falcon", role = "aut"), person(family = "SQLite Authors", role = "ctb", comment = "for the included SQLite sources"), person("Liam", "Healy", role = "ctb", comment = "for the included SQLite sources"), person(family = "R Consortium", role = "cph"), person(family = "RStudio", role = "cph") )
# Description: Embeds the 'SQLite' database engine in R and provides an interface compliant with the 'DBI' package. The source for the 'SQLite' engine (version 3.8.8.2) is included.
# Depends: R (>= 3.1.0)
# Suggests: DBItest, knitr, rmarkdown, testthat
# Imports: bit64, blob (>= 1.1), DBI (>= 0.4-9), memoise, methods, pkgconfig, Rcpp (>= 0.12.7)
# LinkingTo: Rcpp, BH, plogr
# Encoding: UTF-8
# License: LGPL (>= 2)
# URL: https://github.com/rstats-db/RSQLite
# BugReports: https://github.com/rstats-db/RSQLite/issues
# Collate: 'RcppExports.R' 'SQLiteConnection.R' 'SQLiteDriver.R' 'SQLiteResult.R' 'connect.R' 'copy.R' 'datasetsDb.R' 'deprecated.R' 'export.R' 'extensions.R' 'query.R' 'rownames.R' 'table.R' 'transactions.R' 'utils.R' 'zzz.R'
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-06-18 22:12:09 UTC; muelleki
# Author: Kirill Muller [aut, cre], Hadley Wickham [aut], David A. James [aut], Seth Falcon [aut], SQLite Authors [ctb] (for the included SQLite sources), Liam Healy [ctb] (for the included SQLite sources), R Consortium [cph], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2017-06-19 11:51:07 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
