{% set version = '2.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsqlite
  version: {{ version|replace("-", "_") }}

source:
  fn: RSQLite_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/RSQLite_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RSQLite/RSQLite_{{ version }}.tar.gz
  sha256: ad6081be2885be5921b1a44b1896e6a8568c8cff40789f43bfaac9f818767642

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: DBItest, knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-bh
    - r-dbi >=0.8
    - r-rcpp >=0.12.7
    - r-bit64
    - r-blob >=1.1.1
    - r-memoise
    - r-pkgconfig
    - r-plogr >=0.2.0

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-dbi >=0.8
    - r-rcpp >=0.12.7
    - r-bit64
    - r-blob >=1.1.1
    - r-memoise
    - r-pkgconfig
    - r-plogr >=0.2.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RSQLite')"           # [not win]
    - "\"%R%\" -e \"library('RSQLite')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-dbi/RSQLite
  license: LGPL (>= 2)
  summary: Embeds the 'SQLite' database engine in R and provides an interface compliant with
    the 'DBI' package. The source for the 'SQLite' engine is included.
  license_family: LGPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: RSQLite
# Title: 'SQLite' Interface for R
# Version: 2.1.0
# Date: 2018-03-29
# Authors@R: c( person("Kirill", "M\u00fcller", role = c("aut", "cre"), email = "krlmlr+r@mailbox.org", comment = c(ORCID = "0000-0002-1416-3412")), person("Hadley", "Wickham", role = c("aut")), person(c("David", "A."), "James", role = "aut"), person("Seth", "Falcon", role = "aut"), person(family = "SQLite Authors", role = "ctb", comment = "for the included SQLite sources"), person("Liam", "Healy", role = "ctb", comment = "for the included SQLite sources"), person(family = "R Consortium", role = "fnd"), person(family = "RStudio", role = "cph") )
# Description: Embeds the 'SQLite' database engine in R and provides an interface compliant with the 'DBI' package. The source for the 'SQLite' engine is included.
# License: LGPL (>= 2)
# URL: https://github.com/r-dbi/RSQLite
# BugReports: https://github.com/r-dbi/RSQLite/issues
# Depends: R (>= 3.1.0)
# Imports: bit64, blob (>= 1.1.1), DBI (>= 0.8), memoise, methods, pkgconfig, Rcpp (>= 0.12.7)
# Suggests: DBItest, knitr, rmarkdown, testthat
# LinkingTo: BH, plogr (>= 0.2.0), Rcpp
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 6.0.1.9000
# Collate: 'RcppExports.R' 'SQLiteConnection.R' 'SQLiteDriver.R' 'SQLiteResult.R' 'coerce.R' 'connect.R' 'copy.R' 'datasetsDb.R' 'deprecated.R' 'export.R' 'extensions.R' 'query.R' 'rownames.R' 'table.R' 'transactions.R' 'utils.R' 'zzz.R'
# NeedsCompilation: yes
# Packaged: 2018-03-29 19:52:32 UTC; muelleki
# Author: Kirill Muller [aut, cre] (<https://orcid.org/0000-0002-1416-3412>), Hadley Wickham [aut], David A. James [aut], Seth Falcon [aut], SQLite Authors [ctb] (for the included SQLite sources), Liam Healy [ctb] (for the included SQLite sources), R Consortium [fnd], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2018-03-29 21:58:27 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
