travis:
  secure:
    BINSTAR_TOKEN: HaxmL6Ekc5YMtLSJt3XKhyH8JaWpvfEvhaMHPcJ5Jq1F8iaxLuxysTtbgu0UBRBVzjjPrjTD1R2mD+96NA5Imwr6VmT220bc1zilKuFTPVo2+fHMcQb1gCc66VnFz8iWkLCfqTbpvpT1C2jKJ7MMdqt4QRI1WGkBdfLjVYATCxmwpF/TtM3+o26mVvg5Q2xhrHxQk36Tz70HRmU2mj9Jj5HdIFQ4JL/FpLZi2gBlT0pr930XgN7VOWk1x+RBFMr3VRyBYCXCxBptnAwP4KCghBwZNDzITgq344qrFOFSD9GFVTQdk33j56P4NF/kfy4F5pTCILRYfBoIIAjmj6gyf8io3Zl5/NNlDR5BQH9Do6fThKtfIlnaGkvmEAxuMNGmPWCp4BbwIn/2n/4Sr6QTtJQCChLrA1bXM/6J/Y9PhoTte2kdhnsN2XJSpLYU/0fkPQhBHW/E3LGcU8Y3TTXMKAqf6eTyTr7oFSmmcIF4s/uTNTD/F8glLE7AQqqhf0DBQH6oRUWHGZRYEIvV14aSi94yNVhkgc6iT5Eo/dBgKebC9tN2HWkGG+SzeXMnWJtLyIQJBX/o+fNSJ00FgnfETPDK/xaIvsqYN1YMucPF+i9C0pwLaanVvWct0vZkW7oEKo4JY4ffDV/KDucUDD4iuqYscBppiOfOTIKskEJuvJo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
